const words = {
    "nouns": [
      "apple", "banana", "car", "dog", "cat", "house", "tree", "flower", "book", "pen",
      "computer", "phone", "chair", "table", "bird", "ocean", "mountain", "river", "sun", "moon",
      "star", "cloud", "friend", "family", "love", "happiness", "joy", "peace", "hope", "child", "parent",
      "teacher", "student", "doctor", "hospital", "money", "job", "music", "movie", "food", "water",
      "air", "fire", "earth", "universe", "city", "country", "road", "school", "beach", "football", "team",
      "village", "art", "painting", "artist", "guitar", "language", "knowledge", "strength", "determination",
      "dream", "smile", "laughter", "childhood", "memory", "experience", "adventure", "journey", "time", "history",
      "future", "past", "present", "dreams", "hobbies", "nature", "beauty", "health", "technology", "space",
      "planet", "friendship", "communication", "internet", "science", "discovery", "energy", "environment", "freedom",
      "peace", "justice", "equality", "creativity", "imagination", "inspiration", "passion", "surprise", "secret",
      "beach", "money", "peace", "car", "love", "family", "knowledge", "water", "music", "book",
      "tree", "mountain", "friend", "flower", "ocean", "sun", "school", "bird", "cat", "city",
      "table", "computer", "chair", "pen", "dog", "hospital", "road", "moon", "star", "phone",
      "job", "child", "guitar", "happiness", "team", "country", "river", "art", "fire", "experience",
      "determination", "future", "painting", "nature", "earth", "food", "smile", "village", "history", "memory",
      "hope", "technology", "dream", "air", "secret", "adventure", "laughter", "universe", "movie", "friendship", "imagination",
      "discovery", "passion", "dreams", "internet", "teacher", "childhood", "communication", "artist", "football", "planet", "water",
      "energy", "guitar", "creativity", "journey", "beauty", "health", "city", "peace", "time", "dream", "language",
      "knowledge", "inspiration", "science", "equality", "freedom", "environment", "imagination", "smile", "passion", "creativity",
      "adventure", "discovery", "friendship", "memory", "knowledge", "happiness", "communication", "water", "family", "planet",
      "guitar", "time", "road", "internet", "imagination", "star", "child", "fire", "beach", "book", "history",
      "art", "movie", "food", "energy", "school", "sun", "dreams", "childhood", "cat", "table", "science",
      "bird", "music", "ocean", "earth", "communication", "river", "experience", "chair", "job", "painting", "space",
      "knowledge", "mountain", "friend", "team", "money", "future", "guitar", "history", "health", "secret", "family",
      "dream", "hospital", "city", "love", "memory", "phone", "technology", "environment", "village", "planet", "peace",
      "passion", "road", "discovery", "adventure", "equality", "dreams", "beauty", "inspiration", "happiness", "art", "journey",
      "imagination", "internet", "space", "computer", "nature", "beach", "freedom", "friendship", "determination", "flower", "laughter",
      "universe", "time", "hope", "dream", "bird", "smile", "chair", "music", "table", "pen", "fire",
      "teacher", "football", "language", "book", "planet", "cat", "mountain", "city", "guitar", "water", "star"
    ],
    "adjectives": [
        "happy", "sad", "bright", "dark", "small", "big", "beautiful", "ugly", "loud", "quiet",
        "exciting", "boring", "brave", "fearful", "hot", "cold", "fast", "slow", "strong", "weak",
        "colorful", "dull", "joyful", "mournful", "delicious", "bland", "vibrant", "dull", "energetic", "lazy",
        "tall", "short", "cheerful", "gloomy", "friendly", "unfriendly", "determined", "indecisive", "confident", "doubtful",
        "clean", "dirty", "rich", "poor", "generous", "selfish", "polite", "rude", "calm", "nervous",
        "brilliant", "dull", "creative", "unimaginative", "curious", "indifferent", "smart", "dumb", "funny", "serious",
        "modern", "ancient", "healthy", "unhealthy", "spacious", "cramped", "peaceful", "chaotic", "kind", "cruel",
        "wise", "foolish", "calm", "stormy", "gorgeous", "plain", "pleasant", "unpleasant", "sweet", "bitter",
        "humble", "arrogant", "honest", "dishonest", "gentle", "harsh", "lively", "lifeless", "lucky", "unlucky",
        "noisy", "quiet", "organized", "disorganized", "patient", "impatient", "proud", "ashamed", "reliable", "unreliable",
        "peaceful", "warlike", "successful", "unsuccessful", "thoughtful", "thoughtless", "vivid", "dull", "witty", "dull",
        "charming", "repulsive", "vocal", "silent", "logical", "illogical", "hardworking", "lazy", "romantic", "practical",
        "fancy", "simple", "intelligent", "unintelligent", "attractive", "unattractive", "alert", "drowsy", "punctual", "tardy",
        "friendly", "hostile", "tense", "relaxed", "mysterious", "transparent", "helpful", "unhelpful", "cooperative", "uncooperative",
        "proud", "humble", "warm", "cold", "adorable", "repugnant", "capable", "incapable", "expressive", "unexpressive",
        "popular", "unpopular", "graceful", "awkward", "flexible", "inflexible", "energetic", "listless", "confident", "doubtful",
        "skilled", "unskilled", "grateful", "ungrateful", "friendly", "unfriendly", "loyal", "disloyal", "sincere", "insincere",
        "generous", "stingy", "pleased", "displeased", "passionate", "apathetic", "genuine", "fake", "real", "fake",
        "spontaneous", "planned", "courageous", "cowardly", "mature", "immature", "shy", "outgoing", "responsible", "irresponsible",
        "successful", "unsuccessful", "modest", "arrogant", "organized", "disorganized", "polite", "impolite", "creative", "uncreative",
        "loyal", "disloyal", "grateful", "ungrateful", "active", "inactive", "productive", "unproductive", "educated", "uneducated",
        "helpful", "unhelpful", "colorful", "colorless", "tasteful", "tasteless", "adorable", "repugnant", "pleasing", "displeasing",
        "quick", "slow", "delightful", "unpleasant", "exciting", "boring", "delicate", "rough", "pleasant", "unpleasant",
        "certain", "uncertain", "bright", "dim", "compassionate", "heartless", "faithful", "unfaithful", "shiny", "dull",
        "amazing", "ordinary", "harmonious", "discordant", "fascinating", "mundane", "adventurous", "cautious", "radiant", "dull"
      ],
      "verbs": [
        "run", "walk", "jump", "sing", "dance", "swim", "read", "write", "speak", "listen",
        "think", "dream", "laugh", "cry", "eat", "drink", "sleep", "wake", "work", "play",
        "study", "teach", "learn", "explore", "travel", "drive", "fly", "build", "create", "destroy",
        "love", "hate", "forgive", "remember", "forget", "forgive", "apologize", "argue", "bake", "cook",
        "clean", "decorate", "exercise", "paint", "compose", "sing", "dance", "skate", "ski", "hike",
        "climb", "row", "sail", "bike", "cycle", "jog", "garden", "meditate", "yoga", "surf",
        "chase", "catch", "release", "hug", "kiss", "date", "marry", "divorce", "break", "fix",
        "buy", "sell", "invest", "save", "earn", "spend", "shop", "compare", "improve", "repair",
        "win", "lose", "compete", "practice", "perform", "celebrate", "party", "organize", "volunteer", "help",
        "support", "promote", "encourage", "inspire", "motivate", "lead", "follow", "guide", "direct", "manage"
      ]
  }




export default words;